DROP TABLE AUTH;
DROP TABLE MEMBER;

SELECT * FROM BOARD;
SELECT * FROM MEMBER;

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('안녕','머해','혜림');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('안녕1','잘지내','혜림');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('안녕2','자?','혜림');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('안녕3','배고파','혜림');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('안녕4','하2','혜림');